name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build --build-arg PIP_EXTRA_INDEX_URL=https://ZzHEn6GN4KDJqpEefbKj:@pypi.fury.io/himanshuatnagarro . --file Dockerfile --tag shivdotjs/mlops:1.0.0
    - name: List docker images
      run: docker images
    - name: Login to docker hub to push image build
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Push docker image updatev1
      run: docker push shivdotjs/mlops:1.0.0
