# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - containerisedfastapideployment

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_12c532b5d99245e18ffa225757b3f1ca }}
        password: ${{ secrets.AzureAppService_ContainerPassword_3d41b3d63d3d42f390a81a670cac27a7 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_12c532b5d99245e18ffa225757b3f1ca }}/himanshuatnagarro/mlops:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'containerisedfastapideployment'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_4f5d8616f2e44d0cb374db1d24c404b8 }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_12c532b5d99245e18ffa225757b3f1ca }}/himanshuatnagarro/mlops:${{ github.sha }}'