# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - containerisedfastapideployment

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image.
      run: docker build --build-arg PIP_EXTRA_INDEX_URL=https://ZzHEn6GN4KDJqpEefbKj:@pypi.fury.io/himanshuatnagarro . --file Dockerfile --tag himanshuatnagarro/mlops:1.0.0
    - name: List docker images
      run: docker images
    - name: Login to docker hub to push image build
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Push docker image updatev1
      run: docker push himanshuatnagarro/mlops:1.0.0

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'containerisedfastapideployment'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_4f5d8616f2e44d0cb374db1d24c404b8 }}
        images: 'ndex.docker.io/${{ secrets.DOCKERHUB_USERNAME }}/mlops:1.0.0'
